# Generated by Django 2.2.5 on 2019-09-27 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('human_name', models.CharField(default=models.CharField(max_length=50), max_length=50)),
                ('icon', models.ImageField(max_length=255, upload_to='category/%Y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sight%d', max_length=100)),
                ('human_name', models.CharField(default=models.CharField(default='Sight%d', max_length=100), max_length=50)),
                ('description', models.TextField(default='Описание достопримечательности', max_length=2000)),
                ('address', models.CharField(default='Нигде', max_length=25)),
                ('photo', models.ImageField(default=None, max_length=255, upload_to='photo_sights/%Y/%m/%d/')),
                ('web', models.CharField(blank=True, default=None, max_length=75, null=True)),
                ('price', models.IntegerField(default=0)),
                ('longitude', models.CharField(default='00.00000000', max_length=11)),
                ('latitude', models.CharField(default='00.00000000', max_length=11)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainMap.Category')),
            ],
        ),
    ]
